version: "3.5"
services:
  terraform:
    image: hashicorp/terraform:1.3.7
    volumes:
      - ./terraform:/usr/src/infra
    working_dir: /usr/src/infra
    environment:
      # Token de acesso à API da DigitalOcean
      DIGITALOCEAN_ACCESS_TOKEN: ${DIGITALOCEAN_ACCESS_TOKEN}
      # Token de acesso à API do Terraform Cloud
      TF_TOKEN_app_terraform_io: ${TERRAFORM_CLOUD_TOKEN}